services:
  app:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_SHOW_SQL: "true"
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
      MAVEN_OPTS: -Dspring-boot.run.profiles=dev
    volumes:
      - .:/app
      - /root/.m2:/root/.m2
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: postgres
    restart: always
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadmin4
    restart: always
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config.json:/pgadmin4/servers.json

volumes:
  postgres_data:
  pgadmin_data:
