FROM maven:3.9.9-eclipse-temurin-22

WORKDIR /app
COPY pom.xml /app

RUN mvn dependency:go-offline

EXPOSE 8080 5005

ENTRYPOINT ["mvn"]

CMD ["spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]